#!/bin/bash
# Script to apply database migrations
# Usage: bash apply-migration.sh

echo "Applying training records status migration..."
echo ""
echo "To apply this migration, you have two options:"
echo ""
echo "OPTION 1: Using Supabase Dashboard"
echo "1. Go to https://app.supabase.com/project/nszkuoxibzcbiqaqdfml/sql/new"
echo "2. Copy the contents of migrations/add-training-records-status-to-companies.sql"
echo "3. Paste into the SQL editor and click 'Run'"
echo ""
echo "OPTION 2: Using Supabase CLI"
echo "1. Install Supabase CLI: npm install -g supabase"
echo "2. Run: supabase db execute -f migrations/add-training-records-status-to-companies.sql"
echo ""
echo "OPTION 3: Using Node.js (if you have credentials)"
echo "1. Set environment variables:"
echo "   export SUPABASE_URL=https://nszkuoxibzcbiqaqdfml.supabase.co"
echo "   export SUPABASE_SERVICE_ROLE_KEY=<your-service-role-key>"
echo "2. Run: node apply-migration.js"
echo ""
echo "The migration adds the following fields to the companies table:"
echo "  - training_records_status (text): 'none' | 'added' | 'approved' | 'needs_review'"
echo "  - training_records_submitted_at (timestamp)"
echo "  - training_records_approved_at (timestamp)"
echo "  - training_records_last_modified_at (timestamp)"
echo "  - training_records_approved_by (text)"
