#!/bin/bash
# Script to apply Flag/RT migrations to Supabase
# This is required for the kiosk equipment tracking feature to work

echo "🚀 Flag/RT Migration Setup"
echo "=============================="
echo ""
echo "To enable the Flag and RT tracking feature, you need to apply two migrations to your Supabase database."
echo ""
echo "📊 Migrations to apply:"
echo "  1. migrations/add-flag-rt-to-sites.sql - Adds flag and rt columns to sites table"
echo "  2. migrations/add-flag-rt-to-sign-ins.sql - Adds equipment tracking columns to sign_ins table"
echo ""
echo "=================================================="
echo "✅ RECOMMENDED METHOD: Supabase Dashboard"
echo "=================================================="
echo ""
echo "Step 1: Open Supabase Dashboard"
echo "  Go to: https://app.supabase.com/project/nszkuoxibzcbiqaqdfml/sql/new"
echo ""
echo "Step 2: Apply first migration (Sites)"
echo "  1. Copy the contents of: migrations/add-flag-rt-to-sites.sql"
echo "  2. Paste into the SQL editor"
echo "  3. Click the 'Run' button (or press Cmd+Enter)"
echo "  4. You should see: '✓' indicating success"
echo ""
echo "Step 3: Apply second migration (Sign-ins)"
echo "  1. Go back to: https://app.supabase.com/project/nszkuoxibzcbiqaqdfml/sql/new"
echo "  2. Copy the contents of: migrations/add-flag-rt-to-sign-ins.sql"
echo "  3. Paste into the SQL editor"
echo "  4. Click 'Run'"
echo "  5. You should see: '✓' indicating success"
echo ""
echo "Step 4: Test the feature"
echo "  1. Refresh the kiosk page"
echo "  2. Try signing in a contractor at a site with Flag/RT enabled"
echo "  3. You should now see the equipment questions modal"
echo ""
echo "=================================================="
echo "🔧 ALTERNATIVE METHOD: Supabase CLI"
echo "=================================================="
echo ""
echo "If you have the Supabase CLI installed:"
echo "  supabase db execute -f migrations/add-flag-rt-to-sites.sql"
echo "  supabase db execute -f migrations/add-flag-rt-to-sign-ins.sql"
echo ""
echo "=================================================="
echo ""
echo "❓ If you still have issues after applying migrations:"
echo "  1. Check browser console (F12) for error messages"
echo "  2. Verify Supabase project is running"
echo "  3. Clear browser cache and refresh"
echo ""
